server:
  port: 8085
  
spring:
  application:
    name: CONFIG_SERVER
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PrathmeshJ-java/Microservices_configuration
          clone-on-start: true
       